import { prisma } from "../../../../lib/prisma";
import { auth } from "../../../../auth";
import { resolveReportScope } from "../../../../lib/report-scope";
import { buildFrameworkPath } from "../../../../lib/framework-path";
import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

const SECTOR_LABELS = {
  education: "Education", economic: "Women's Economic Empowerment", rights: "Rights & Leadership",
  health: "Health", water: "Water", climate: "Climate Change",
};
const SECTOR_COLORS = {
  education: "#1B3A5C", economic: "#D9A441", rights: "#B8442D",
  health: "#8C4A6B", water: "#2E7D8C", climate: "#5C7A3D",
};
const COLORS = { ink: "#241D18", muted: "#665f52", line: "#DED2BC", card: "#FBF8F2", navy: "#1B3A5C", red: "#B8442D", gold: "#D9A441", green: "#5C7A3D" };
const PAGE_W = 595.28, MARGIN = 50, CONTENT_W = PAGE_W - MARGIN * 2;

function streamToBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}

function checkPageBreak(doc, neededHeight) {
  if (doc.y + neededHeight > doc.page.height - 60) {
    doc.addPage();
  }
}

function drawPill(doc, x, y, text, bg, fg) {
  doc.font("Helvetica-Bold").fontSize(8);
  const w = doc.widthOfString(text) + 14;
  doc.roundedRect(x, y, w, 15, 7.5).fill(bg);
  doc.fillColor(fg).text(text, x, y + 4, { width: w, align: "center" });
  doc.font("Helvetica");
  return w;
}

function drawProgressBar(doc, x, y, w, pct) {
  const color = pct >= 80 ? COLORS.green : pct >= 40 ? COLORS.gold : COLORS.red;
  doc.roundedRect(x, y, w, 6, 3).fill("#EDE6D8");
  doc.roundedRect(x, y, Math.max((w * Math.min(pct, 100)) / 100, 6), 6, 3).fill(color);
}

function writeHeader(doc, title, subtitle) {
  const logoPath = path.join(process.cwd(), "public", "pwc-logo.png");
  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, MARGIN, 40, { width: 44 });
    doc.font("Helvetica-Bold").fontSize(17).fillColor(COLORS.navy).text(title, MARGIN + 54, 42, { width: CONTENT_W - 54 });
    doc.font("Helvetica").fontSize(9.5).fillColor(COLORS.muted).text(subtitle, MARGIN + 54, 63, { width: CONTENT_W - 54 });
  } else {
    doc.font("Helvetica-Bold").fontSize(19).fillColor(COLORS.navy).text(title);
  }
  doc.y = 95;
  doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + CONTENT_W, doc.y).lineWidth(1).strokeColor(COLORS.line).stroke();
  doc.moveDown(1);
}

function writeMetaBar(doc, { periodLabel, scopeLabel, generatedBy }) {
  const boxY = doc.y;
  const boxH = 34;
  doc.roundedRect(MARGIN, boxY, CONTENT_W, boxH, 6).fill(COLORS.card);
  doc.font("Helvetica-Bold").fontSize(8.5).fillColor(COLORS.muted)
    .text("PERIOD", MARGIN + 14, boxY + 7)
    .text("SCOPE", MARGIN + 220, boxY + 7)
    .text("GENERATED BY", MARGIN + 380, boxY + 7);
  doc.font("Helvetica").fontSize(9.5).fillColor(COLORS.ink)
    .text(periodLabel, MARGIN + 14, boxY + 18, { width: 195 })
    .text(scopeLabel, MARGIN + 220, boxY + 18, { width: 150 })
    .text(generatedBy, MARGIN + 380, boxY + 18, { width: 165 });
  doc.y = boxY + boxH + 18;
}

function writeSectionTitle(doc, text) {
  checkPageBreak(doc, 30);
  doc.font("Helvetica-Bold").fontSize(13).fillColor(COLORS.ink).text(text);
  doc.moveDown(0.5);
}

function drawStatCards(doc, cards) {
  const gap = 10;
  const w = (CONTENT_W - gap * (cards.length - 1)) / cards.length;
  const y = doc.y;
  cards.forEach((c, i) => {
    const x = MARGIN + i * (w + gap);
    doc.roundedRect(x, y, w, 52, 6).fillAndStroke(COLORS.card, COLORS.line);
    doc.font("Helvetica").fontSize(7.5).fillColor(COLORS.muted).text(c.label.toUpperCase(), x + 10, y + 9, { width: w - 20 });
    doc.font("Helvetica-Bold").fontSize(16).fillColor(c.color || COLORS.ink).text(String(c.value), x + 10, y + 24, { width: w - 20 });
  });
  doc.y = y + 52 + 18;
}

function groupIndicatorsByPath(p, frameworkNodes) {
  // Groups indicators that share the same results-framework path so the
  // path is shown once per group instead of repeated before every indicator.
  const nodes = frameworkNodes || p.frameworkNodes || [];
  const groups = [];
  const byPath = {};
  p.indicators.forEach((i) => {
    const fPath = buildFrameworkPath(nodes, i.frameworkNodeId);
    const key = fPath || "__unplaced__";
    if (!byPath[key]) {
      byPath[key] = { fPath, indicators: [] };
      groups.push(byPath[key]);
    }
    byPath[key].indicators.push(i);
  });
  return groups;
}

function drawProjectCard(doc, p, frameworkNodes) {
  const sectorColor = SECTOR_COLORS[p.sector] || COLORS.navy;
  const groups = groupIndicatorsByPath(p, frameworkNodes);
  const pathFont = { name: "Helvetica-Oblique", size: 7.5 };
  const pathWidth = CONTENT_W - 32;

  // Measure real heights up front so nothing overlaps, regardless of how
  // long a framework path wraps.
  let estHeight = 34 + 14 + 20;
  const measuredPaths = groups.map((g) => {
    let pathH = 0;
    if (g.fPath) {
      doc.font(pathFont.name).fontSize(pathFont.size);
      pathH = doc.heightOfString(g.fPath, { width: pathWidth }) + 4;
    }
    estHeight += pathH + g.indicators.length * 29;
    return pathH;
  });
  checkPageBreak(doc, Math.min(estHeight, 550));

  const startY = doc.y;
  const cardX = MARGIN;
  let cursorY = startY + 14;

  doc.save();
  doc.roundedRect(cardX, startY, CONTENT_W, estHeight, 8).fill(COLORS.card);
  doc.rect(cardX, startY, 4, estHeight).fill(sectorColor);
  doc.restore();

  doc.font("Helvetica-Bold").fontSize(12.5).fillColor(COLORS.ink).text(p.name, cardX + 16, cursorY, { width: CONTENT_W - 32 });
  cursorY += 17;

  const sectorLabel = SECTOR_LABELS[p.sector] || p.sector;
  let pillX = cardX + 16;
  const w1 = drawPill(doc, pillX, cursorY, sectorLabel, sectorColor + "22", sectorColor);
  pillX += w1 + 6;
  if (p.status) {
    const w2 = drawPill(doc, pillX, cursorY, p.status, "#E4EBD9", COLORS.green);
    pillX += w2 + 6;
  }
  doc.font("Helvetica").fontSize(8.5).fillColor(COLORS.muted)
    .text(`${p.district}  ·  Coordinator: ${p.coordinator ? p.coordinator.name : "Unassigned"}  ·  Donor: ${p.donorContact ? p.donorContact.name : "Unassigned"}`, pillX + 4, cursorY + 3, { width: cardX + CONTENT_W - pillX - 20 });
  cursorY += 24;

  groups.forEach((g, gi) => {
    if (g.fPath) {
      doc.font(pathFont.name).fontSize(pathFont.size).fillColor(COLORS.gold)
        .text(g.fPath, cardX + 16, cursorY, { width: pathWidth });
      cursorY += measuredPaths[gi];
    }
    g.indicators.forEach((i) => {
      const pct = i.target > 0 ? Math.round((i.actual / i.target) * 100) : 0;
      doc.font("Helvetica").fontSize(9.5).fillColor(COLORS.ink).text(i.name, cardX + 16, cursorY, { width: CONTENT_W - 180 });
      doc.font("Helvetica-Bold").fontSize(9.5).fillColor(COLORS.ink).text(`${i.actual}/${i.target} ${i.unit} (${pct}%)`, cardX + CONTENT_W - 170, cursorY, { width: 154, align: "right" });
      cursorY += 13;
      drawProgressBar(doc, cardX + 16, cursorY, CONTENT_W - 32, pct);
      cursorY += 16;
    });
  });

  doc.y = startY + estHeight + 12;
}

function drawSimpleCard(doc, renderFn, estHeight) {
  checkPageBreak(doc, estHeight);
  const startY = doc.y;
  doc.roundedRect(MARGIN, startY, CONTENT_W, estHeight, 8).fillAndStroke(COLORS.card, COLORS.line);
  renderFn(startY + 14);
  doc.y = startY + estHeight + 10;
}

function addPageNumbers(doc) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);
    doc.font("Helvetica").fontSize(8).fillColor(COLORS.muted)
      .text(`Page ${i + 1} of ${range.count}  ·  Confidential — for authorized recipients only`, MARGIN, doc.page.height - 40, { width: CONTENT_W, align: "center" });
  }
}

export async function GET(request) {
  const session = await auth();
  const { searchParams } = new URL(request.url);
  const requestId = searchParams.get("requestId");

  let startDate = searchParams.get("start") || "";
  let endDate = searchParams.get("end") || "";
  let projectFilter = searchParams.get("project") || "all";
  let reportType = searchParams.get("reportType") || "programme_summary";

  if (requestId) {
    const rr = await prisma.reportRequest.findUnique({ where: { id: Number(requestId) } });
    if (rr) {
      startDate = rr.startDate ? rr.startDate.toISOString().slice(0, 10) : "";
      endDate = rr.endDate ? rr.endDate.toISOString().slice(0, 10) : "";
      projectFilter = rr.projectId ? String(rr.projectId) : "all";
      reportType = rr.reportType;
    }
  }

  const { allowedProjects, scopedProjectIds } = await resolveReportScope(session, projectFilter);
  const dateWhere = {};
  if (startDate) dateWhere.gte = new Date(startDate);
  if (endDate) dateWhere.lte = new Date(endDate + "T23:59:59");

  const periodLabel = startDate || endDate ? `${startDate || "Start"} to ${endDate || "Present"}` : "All time";
  const scopeLabel = projectFilter === "all" ? `${scopedProjectIds.length} project(s) in scope` : (allowedProjects.find((p) => p.id === Number(projectFilter))?.name || "Selected project");
  const generatedBy = session?.user?.name || "PWC M&E Platform";

  const doc = new PDFDocument({ margin: MARGIN, size: "A4", bufferPages: true });
  doc.on("pageAdded", () => {});

  if (reportType === "beneficiaries") {
    writeHeader(doc, "Beneficiary Register Report", "Pastoral Women's Council · Cloud-Based M&E Platform");
    writeMetaBar(doc, { periodLabel, scopeLabel, generatedBy });

    const beneficiaries = await prisma.beneficiary.findMany({
      where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { enrolled: dateWhere } : {}) },
      include: { project: true }, orderBy: { id: "desc" },
    });

    drawStatCards(doc, [{ label: "Total beneficiaries", value: beneficiaries.length, color: COLORS.navy }]);
    writeSectionTitle(doc, "Registered Beneficiaries");

    beneficiaries.forEach((b) => {
      drawSimpleCard(doc, (y) => {
        doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.ink).text(b.name, MARGIN + 16, y, { width: CONTENT_W - 160 });
        doc.font("Helvetica").fontSize(8.5).fillColor(COLORS.muted).text(`${b.sex}, age ${b.age}  ·  ${b.district}  ·  ${b.project ? b.project.name : "No project"}${b.phone ? "  ·  " + b.phone : ""}`, MARGIN + 16, y + 14, { width: CONTENT_W - 32 });
      }, 44);
    });

  } else if (reportType === "risks") {
    writeHeader(doc, "Risk Register Report", "Pastoral Women's Council · Cloud-Based M&E Platform");
    writeMetaBar(doc, { periodLabel, scopeLabel, generatedBy });

    const risks = await prisma.risk.findMany({
      where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { createdAt: dateWhere } : {}) },
      include: { project: true }, orderBy: { id: "desc" },
    });
    const levelColor = { Low: COLORS.green, Medium: COLORS.gold, High: COLORS.red };

    drawStatCards(doc, [
      { label: "Total risks", value: risks.length, color: COLORS.navy },
      { label: "Open", value: risks.filter((r) => r.status === "Open").length, color: COLORS.gold },
      { label: "High priority", value: risks.filter((r) => r.likelihood === "High" || r.impact === "High").length, color: COLORS.red },
    ]);
    writeSectionTitle(doc, "Logged Risks");

    risks.forEach((r) => {
      const estH = 30 + (r.mitigation ? 12 : 0) + 12;
      drawSimpleCard(doc, (y) => {
        doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.ink).text(r.title, MARGIN + 16, y, { width: CONTENT_W - 190 });
        let px = MARGIN + CONTENT_W - 170;
        drawPill(doc, px, y - 2, r.likelihood, (levelColor[r.likelihood] || COLORS.gold) + "22", levelColor[r.likelihood] || COLORS.gold);
        drawPill(doc, px + 55, y - 2, r.status, "#DDE6EE", COLORS.navy);
        doc.font("Helvetica").fontSize(8.5).fillColor(COLORS.muted).text(`${r.project ? r.project.name : "No project"}${r.description ? "  ·  " + r.description : ""}`, MARGIN + 16, y + 14, { width: CONTENT_W - 32 });
        if (r.mitigation) {
          doc.font("Helvetica-Oblique").fontSize(8).fillColor(COLORS.green).text(`Mitigation: ${r.mitigation}`, MARGIN + 16, y + 26, { width: CONTENT_W - 32 });
        }
      }, estH + 20);
    });

  } else if (reportType === "feedback") {
    writeHeader(doc, "Feedback & Complaints Report", "Pastoral Women's Council · Cloud-Based M&E Platform");
    writeMetaBar(doc, { periodLabel, scopeLabel, generatedBy });

    const feedback = await prisma.feedback.findMany({
      where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { createdAt: dateWhere } : {}) },
      include: { project: true }, orderBy: { id: "desc" },
    });
    const catColor = { Complaint: COLORS.red, Suggestion: COLORS.gold, Feedback: COLORS.green };

    drawStatCards(doc, [
      { label: "Total logged", value: feedback.length, color: COLORS.navy },
      { label: "Open", value: feedback.filter((f) => f.status === "Open").length, color: COLORS.gold },
      { label: "Resolved", value: feedback.filter((f) => f.status === "Resolved").length, color: COLORS.green },
    ]);
    writeSectionTitle(doc, "Feedback & Complaints");

    feedback.forEach((f) => {
      drawSimpleCard(doc, (y) => {
        drawPill(doc, MARGIN + 16, y, f.category, (catColor[f.category] || COLORS.navy) + "22", catColor[f.category] || COLORS.navy);
        doc.font("Helvetica").fontSize(8.5).fillColor(COLORS.muted).text(`${f.district}  ·  ${f.project ? f.project.name : "No project"}  ·  ${f.status}  ·  ${f.createdAt.toISOString().slice(0, 10)}`, MARGIN + 90, y + 3, { width: CONTENT_W - 106 });
        doc.font("Helvetica").fontSize(9.5).fillColor(COLORS.ink).text(f.note, MARGIN + 16, y + 20, { width: CONTENT_W - 32 });
      }, 50);
    });

  } else if (reportType === "projects_indicators") {
    writeHeader(doc, "Projects & Indicators Report", "Pastoral Women's Council · Cloud-Based M&E Platform");
    writeMetaBar(doc, { periodLabel, scopeLabel, generatedBy });

    const projects = await prisma.project.findMany({
      where: { id: { in: scopedProjectIds } },
      include: { indicators: true, coordinator: true, donorContact: true, frameworkNodes: true },
    });

    writeSectionTitle(doc, "Project Detail");
    projects.forEach((p) => drawProjectCard(doc, p, p.frameworkNodes));

  } else {
    writeHeader(doc, "Programme Summary Report", "Pastoral Women's Council · Cloud-Based M&E Platform");
    writeMetaBar(doc, { periodLabel, scopeLabel, generatedBy });

    const [projects, beneficiaryCount, feedbackList] = await Promise.all([
      prisma.project.findMany({ where: { id: { in: scopedProjectIds } }, include: { indicators: true, coordinator: true, donorContact: true, frameworkNodes: true } }),
      prisma.beneficiary.count({ where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { enrolled: dateWhere } : {}) } }),
      prisma.feedback.findMany({ where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { createdAt: dateWhere } : {}) } }),
    ]);

    const totalTarget = projects.reduce((a, p) => a + p.indicators.reduce((x, i) => x + i.target, 0), 0);
    const totalActual = projects.reduce((a, p) => a + p.indicators.reduce((x, i) => x + i.actual, 0), 0);
    const overallPct = totalTarget > 0 ? Math.round((totalActual / totalTarget) * 100) : 0;

    drawStatCards(doc, [
      { label: "Overall achievement", value: `${overallPct}%`, color: COLORS.navy },
      { label: "Projects in scope", value: projects.length, color: COLORS.green },
      { label: "Beneficiaries", value: beneficiaryCount, color: COLORS.gold },
      { label: "Feedback items", value: feedbackList.length, color: COLORS.red },
    ]);

    writeSectionTitle(doc, "Sector Performance");
    checkPageBreak(doc, 30 * Object.keys(SECTOR_LABELS).length);
    Object.entries(SECTOR_LABELS).forEach(([id, label]) => {
      const sp = projects.filter((p) => p.sector === id);
      const t = sp.reduce((a, p) => a + p.indicators.reduce((x, i) => x + i.target, 0), 0);
      const ac = sp.reduce((a, p) => a + p.indicators.reduce((x, i) => x + i.actual, 0), 0);
      if (t === 0) return;
      const pct = Math.round((ac / t) * 100);
      doc.font("Helvetica").fontSize(9.5).fillColor(COLORS.ink).text(label, MARGIN, doc.y, { continued: false });
      doc.font("Helvetica-Bold").fontSize(9.5).text(`${pct}%`, MARGIN + CONTENT_W - 50, doc.y - 12, { width: 50, align: "right" });
      drawProgressBar(doc, MARGIN, doc.y + 2, CONTENT_W, pct);
      doc.y += 16;
    });
    doc.moveDown(0.8);

    writeSectionTitle(doc, "Project Detail");
    projects.forEach((p) => drawProjectCard(doc, p, p.frameworkNodes));
  }

  addPageNumbers(doc);

  const buffer = await streamToBuffer(doc);
  const filename = `PWC-${reportType}-${new Date().toISOString().slice(0, 10)}.pdf`;

  return new Response(buffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
