import { prisma } from "../../../../lib/prisma";
import { auth } from "../../../../auth";
import { resolveReportScope } from "../../../../lib/report-scope";
import { buildFrameworkPath } from "../../../../lib/framework-path";
import ExcelJS from "exceljs";
import fs from "fs";
import path from "path";

const SECTOR_LABELS = {
  education: "Education", economic: "Women's Economic Empowerment", rights: "Rights & Leadership",
  health: "Health", water: "Water", climate: "Climate Change",
};

const NAVY = "FF1B3A5C", CARD = "FFFBF8F2", ZEBRA = "FFF3EDE0", GREEN = "FF5C7A3D", GOLD = "FFD9A441", RED = "FFB8442D";
const GREEN_BG = "FFE4EBD9", GOLD_BG = "FFF6E7CC", RED_BG = "FFF3DCD4";

const headerFill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
const headerFont = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
const thinBorder = { style: "thin", color: { argb: "FFDED2BC" } };

function styleHeaderRow(sheet) {
  const row = sheet.getRow(1);
  row.eachCell((cell) => {
    cell.fill = headerFill;
    cell.font = headerFont;
    cell.alignment = { vertical: "middle" };
    cell.border = { top: thinBorder, bottom: thinBorder, left: thinBorder, right: thinBorder };
  });
  row.height = 20;
  sheet.views = [{ state: "frozen", ySplit: 1 }];
  const lastCol = sheet.columns.length;
  const colLetter = String.fromCharCode(64 + lastCol) + (lastCol > 26 ? "" : "");
  try {
    sheet.autoFilter = { from: "A1", to: `${sheet.getColumn(lastCol).letter}1` };
  } catch (e) { /* ignore if column count edge case */ }
}

function zebraStripe(sheet, startRow = 2) {
  for (let r = startRow; r <= sheet.rowCount; r++) {
    const row = sheet.getRow(r);
    const isEven = (r - startRow) % 2 === 1;
    row.eachCell({ includeEmpty: true }, (cell) => {
      if (!cell.fill || cell.fill.fgColor?.argb === undefined) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: isEven ? ZEBRA : CARD } };
      }
      cell.border = { bottom: thinBorder };
      // No forced wrapText: long text stays on one line (Excel truncates the
      // display, not the data) so rows can never visually overlap. Users can
      // widen a column or click a cell to see the full value.
      cell.alignment = { ...(cell.alignment || {}), vertical: "middle" };
    });
    row.height = 18;
  }
}

function colorPctColumn(sheet, colKey, startRow = 2) {
  const col = sheet.getColumn(colKey);
  if (!col) return;
  for (let r = startRow; r <= sheet.rowCount; r++) {
    const cell = sheet.getRow(r).getCell(colKey);
    const raw = String(cell.value || "").replace("%", "");
    const pct = Number(raw);
    if (isNaN(pct)) continue;
    const bg = pct >= 80 ? GREEN_BG : pct >= 40 ? GOLD_BG : RED_BG;
    const fg = pct >= 80 ? GREEN : pct >= 40 ? GOLD : RED;
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: bg } };
    cell.font = { bold: true, color: { argb: fg } };
  }
}

function addCoverSheet(workbook, { title, periodLabel, scopeLabel, generatedBy }) {
  const cover = workbook.addWorksheet("Cover");
  cover.columns = [{ width: 4 }, { width: 44 }, { width: 34 }];

  // Reserve fixed-height rows for the logo so text below can never overlap it.
  for (let r = 1; r <= 7; r++) cover.getRow(r).height = 18;

  const logoPath = path.join(process.cwd(), "public", "pwc-logo.png");
  if (fs.existsSync(logoPath)) {
    const logoImageId = workbook.addImage({ filename: logoPath, extension: "png" });
    cover.addImage(logoImageId, { tl: { col: 1, row: 0.3 }, ext: { width: 80, height: 66 } });
  }

  cover.getCell("B9").value = "Pastoral Women's Council";
  cover.getCell("B9").font = { bold: true, size: 20, color: { argb: NAVY } };
  cover.getCell("B10").value = title;
  cover.getCell("B10").font = { size: 14, color: { argb: "FF665F52" } };
  cover.getCell("B11").value = "Cloud-Based M&E Platform";
  cover.getCell("B11").font = { size: 10, italic: true, color: { argb: "FF999999" } };

  const rows = [
    ["Report period:", periodLabel],
    ["Scope:", scopeLabel],
    ["Generated:", new Date().toISOString().slice(0, 10)],
    ["Generated by:", generatedBy],
  ];
  rows.forEach(([label, value], i) => {
    const r = 14 + i;
    cover.getCell(`B${r}`).value = label;
    cover.getCell(`B${r}`).font = { bold: true, size: 10.5 };
    cover.getCell(`C${r}`).value = value;
    cover.getCell(`C${r}`).font = { size: 10.5 };
  });

  cover.getCell("B20").value = "Confidential — for authorized recipients only";
  cover.getCell("B20").font = { italic: true, size: 9, color: { argb: "FF999999" } };
}

export async function GET(request) {
  const session = await auth();
  const { searchParams } = new URL(request.url);
  const requestId = searchParams.get("requestId");

  let startDate = searchParams.get("start") || "";
  let endDate = searchParams.get("end") || "";
  let projectFilter = searchParams.get("project") || "all";
  let reportType = searchParams.get("reportType") || "programme_summary";

  if (requestId) {
    const rr = await prisma.reportRequest.findUnique({ where: { id: Number(requestId) } });
    if (rr) {
      startDate = rr.startDate ? rr.startDate.toISOString().slice(0, 10) : "";
      endDate = rr.endDate ? rr.endDate.toISOString().slice(0, 10) : "";
      projectFilter = rr.projectId ? String(rr.projectId) : "all";
      reportType = rr.reportType;
    }
  }

  const { allowedProjects, scopedProjectIds } = await resolveReportScope(session, projectFilter);
  const dateWhere = {};
  if (startDate) dateWhere.gte = new Date(startDate);
  if (endDate) dateWhere.lte = new Date(endDate + "T23:59:59");

  const periodLabel = startDate || endDate ? `${startDate || "Start"} to ${endDate || "Present"}` : "All time";
  const scopeLabel = projectFilter === "all" ? `${scopedProjectIds.length} project(s) in scope` : (allowedProjects.find((p) => p.id === Number(projectFilter))?.name || "Selected project");
  const generatedBy = session?.user?.name || "PWC M&E Platform";

  const workbook = new ExcelJS.Workbook();
  workbook.creator = "PWC M&E Platform";
  workbook.created = new Date();

  if (reportType === "beneficiaries") {
    addCoverSheet(workbook, { title: "Beneficiary Register Report", periodLabel, scopeLabel, generatedBy });
    const beneficiaries = await prisma.beneficiary.findMany({
      where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { enrolled: dateWhere } : {}) },
      include: { project: true }, orderBy: { id: "desc" },
    });
    const sheet = workbook.addWorksheet("Beneficiaries");
    sheet.columns = [
      { header: "Name", key: "name", width: 24 }, { header: "Phone", key: "phone", width: 16 },
      { header: "Sex", key: "sex", width: 10 }, { header: "Age", key: "age", width: 8 },
      { header: "District", key: "district", width: 18 }, { header: "Sector", key: "sector", width: 16 },
      { header: "Project", key: "project", width: 34 }, { header: "Enrolled", key: "enrolled", width: 14 },
    ];
    beneficiaries.forEach((b) => sheet.addRow({
      name: b.name, phone: b.phone || "", sex: b.sex, age: b.age, district: b.district, sector: b.sector,
      project: b.project ? b.project.name : "", enrolled: b.enrolled.toISOString().slice(0, 10),
    }));
    styleHeaderRow(sheet);
    zebraStripe(sheet);

  } else if (reportType === "risks") {
    addCoverSheet(workbook, { title: "Risk Register Report", periodLabel, scopeLabel, generatedBy });
    const risks = await prisma.risk.findMany({
      where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { createdAt: dateWhere } : {}) },
      include: { project: true }, orderBy: { id: "desc" },
    });
    const sheet = workbook.addWorksheet("Risks");
    sheet.columns = [
      { header: "Title", key: "title", width: 34 }, { header: "Description", key: "description", width: 40 },
      { header: "Likelihood", key: "likelihood", width: 12 }, { header: "Impact", key: "impact", width: 12 },
      { header: "Mitigation", key: "mitigation", width: 40 }, { header: "Status", key: "status", width: 12 },
      { header: "Project", key: "project", width: 30 }, { header: "Logged", key: "logged", width: 14 },
    ];
    risks.forEach((r) => sheet.addRow({
      title: r.title, description: r.description || "", likelihood: r.likelihood, impact: r.impact,
      mitigation: r.mitigation || "", status: r.status, project: r.project ? r.project.name : "",
      logged: r.createdAt.toISOString().slice(0, 10),
    }));
    styleHeaderRow(sheet);
    zebraStripe(sheet);

  } else if (reportType === "feedback") {
    addCoverSheet(workbook, { title: "Feedback & Complaints Report", periodLabel, scopeLabel, generatedBy });
    const feedback = await prisma.feedback.findMany({
      where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { createdAt: dateWhere } : {}) },
      include: { project: true }, orderBy: { id: "desc" },
    });
    const sheet = workbook.addWorksheet("Feedback");
    sheet.columns = [
      { header: "Category", key: "category", width: 14 }, { header: "District", key: "district", width: 14 },
      { header: "Project", key: "project", width: 34 }, { header: "Note", key: "note", width: 50 },
      { header: "Status", key: "status", width: 12 }, { header: "Date", key: "date", width: 14 },
    ];
    feedback.forEach((f) => sheet.addRow({
      category: f.category, district: f.district, project: f.project ? f.project.name : "",
      note: f.note, status: f.status, date: f.createdAt.toISOString().slice(0, 10),
    }));
    styleHeaderRow(sheet);
    zebraStripe(sheet);

  } else if (reportType === "projects_indicators") {
    addCoverSheet(workbook, { title: "Projects & Indicators Report", periodLabel, scopeLabel, generatedBy });
    const projects = await prisma.project.findMany({
      where: { id: { in: scopedProjectIds } },
      include: { indicators: true, coordinator: true, donorContact: true, frameworkNodes: true },
    });
    const sheet = workbook.addWorksheet("Indicators");
    sheet.columns = [
      { header: "Project", key: "project", width: 34 }, { header: "Sector", key: "sector", width: 26 },
      { header: "District", key: "district", width: 14 }, { header: "Status", key: "status", width: 12 },
      { header: "Coordinator", key: "coordinator", width: 20 }, { header: "Donor contact", key: "donor", width: 20 },
      { header: "Results Framework Path", key: "frameworkPath", width: 55 },
      { header: "Indicator", key: "indicator", width: 40 }, { header: "Target", key: "target", width: 12 },
      { header: "Actual", key: "actual", width: 12 }, { header: "Unit", key: "unit", width: 12 },
      { header: "% Achieved", key: "pct", width: 12 },
    ];
    projects.forEach((p) => {
      let lastPath = null;
      p.indicators.forEach((i) => {
        const fPath = buildFrameworkPath(p.frameworkNodes, i.frameworkNodeId) || "Not placed in framework";
        sheet.addRow({
          project: p.name, sector: SECTOR_LABELS[p.sector] || p.sector, district: p.district, status: p.status,
          coordinator: p.coordinator ? p.coordinator.name : "Unassigned", donor: p.donorContact ? p.donorContact.name : "Unassigned",
          frameworkPath: fPath === lastPath ? "" : fPath,
          indicator: i.name, target: i.target, actual: i.actual, unit: i.unit,
          pct: i.target > 0 ? Math.round((i.actual / i.target) * 100) + "%" : "n/a",
        });
        lastPath = fPath;
      });
    });
    styleHeaderRow(sheet);
    zebraStripe(sheet);
    colorPctColumn(sheet, "pct");

  } else {
    addCoverSheet(workbook, { title: "Programme Summary Report", periodLabel, scopeLabel, generatedBy });
    const [projects, beneficiaries, feedback] = await Promise.all([
      prisma.project.findMany({ where: { id: { in: scopedProjectIds } }, include: { indicators: true, coordinator: true, donorContact: true, frameworkNodes: true } }),
      prisma.beneficiary.findMany({ where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { enrolled: dateWhere } : {}) }, include: { project: true } }),
      prisma.feedback.findMany({ where: { projectId: { in: scopedProjectIds }, ...(Object.keys(dateWhere).length ? { createdAt: dateWhere } : {}) }, include: { project: true } }),
    ]);

    const indicatorSheet = workbook.addWorksheet("Indicators");
    indicatorSheet.columns = [
      { header: "Project", key: "project", width: 34 }, { header: "Sector", key: "sector", width: 26 },
      { header: "District", key: "district", width: 14 }, { header: "Coordinator", key: "coordinator", width: 20 },
      { header: "Results Framework Path", key: "frameworkPath", width: 55 },
      { header: "Indicator", key: "indicator", width: 40 }, { header: "Target", key: "target", width: 12 },
      { header: "Actual", key: "actual", width: 12 }, { header: "Unit", key: "unit", width: 12 },
      { header: "% Achieved", key: "pct", width: 12 },
    ];
    projects.forEach((p) => {
      let lastPath = null;
      p.indicators.forEach((i) => {
        const fPath = buildFrameworkPath(p.frameworkNodes, i.frameworkNodeId) || "Not placed in framework";
        indicatorSheet.addRow({
          project: p.name, sector: SECTOR_LABELS[p.sector] || p.sector, district: p.district,
          coordinator: p.coordinator ? p.coordinator.name : "Unassigned",
          frameworkPath: fPath === lastPath ? "" : fPath,
          indicator: i.name, target: i.target, actual: i.actual, unit: i.unit,
          pct: i.target > 0 ? Math.round((i.actual / i.target) * 100) + "%" : "n/a",
        });
        lastPath = fPath;
      });
    });
    styleHeaderRow(indicatorSheet);
    zebraStripe(indicatorSheet);
    colorPctColumn(indicatorSheet, "pct");

    const beneSheet = workbook.addWorksheet("Beneficiaries");
    beneSheet.columns = [
      { header: "Name", key: "name", width: 24 }, { header: "Phone", key: "phone", width: 16 },
      { header: "Sex", key: "sex", width: 10 }, { header: "Age", key: "age", width: 8 },
      { header: "District", key: "district", width: 18 }, { header: "Sector", key: "sector", width: 16 },
      { header: "Project", key: "project", width: 34 }, { header: "Enrolled", key: "enrolled", width: 14 },
    ];
    beneficiaries.forEach((b) => beneSheet.addRow({
      name: b.name, phone: b.phone || "", sex: b.sex, age: b.age, district: b.district, sector: b.sector,
      project: b.project ? b.project.name : "", enrolled: b.enrolled.toISOString().slice(0, 10),
    }));
    styleHeaderRow(beneSheet);
    zebraStripe(beneSheet);

    const fbSheet = workbook.addWorksheet("Feedback");
    fbSheet.columns = [
      { header: "Category", key: "category", width: 14 }, { header: "District", key: "district", width: 14 },
      { header: "Project", key: "project", width: 34 }, { header: "Note", key: "note", width: 50 },
      { header: "Status", key: "status", width: 12 }, { header: "Date", key: "date", width: 14 },
    ];
    feedback.forEach((f) => fbSheet.addRow({
      category: f.category, district: f.district, project: f.project ? f.project.name : "",
      note: f.note, status: f.status, date: f.createdAt.toISOString().slice(0, 10),
    }));
    styleHeaderRow(fbSheet);
    zebraStripe(fbSheet);
  }

  const buffer = await workbook.xlsx.writeBuffer();
  const filename = `PWC-${reportType}-${new Date().toISOString().slice(0, 10)}.xlsx`;

  return new Response(buffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
